FROM python:3.9-slim

WORKDIR /app

COPY . /app

RUN apt-get update && apt-get install -y \
    vim \
    g++ \
    && apt-get clean

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT [ "bin/bash" ]